language: c

sudo: false

matrix:
    include:
        - env: CABALVER=1.16 GHCVER=7.6.3
            addons: {apt: {packages: [cabal-install-1.16,ghc-7.6.3], sources: [hvr-ghc]}}
        - env: CABALVER=1.18 GHCVER=7.8.4
            addons: {apt: {packages: [cabal-install-1.18,ghc-7.8.4], sources: [hvr-ghc]}}
        - env: CABALVER=1.22 GHCVER=7.10.1
            addons: {apt: {packages: [cabal-install-1.22,ghc-7.10.1],sources: [hvr-ghc]}}
        - env: CABALVER=head GHCVER=head
            addons: {apt: {packages: [cabal-install-head,ghc-head],  sources: [hvr-ghc]}}

    allow_failures:
        - env: CABALVER=head GHCVER=head

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
    - cabal update
    - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
    - cabal install hlint --avoid-reinstalls
    - cabal install hspec --avoid-reinstalls
    - cabal install hpc-coveralls --avoid-reinstalls

install:
    - cabal install --only-dependencies --enable-tests --avoid-reinstalls

script:
    - hlint .
    - cabal configure --enable-tests --enable-library-coverage
    - cabal build
    - cabal test --show-details=always

after_script:
    - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test test-all
