language: haskell

ghc:
    - 7.8

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - cabal update
    - cabal install hlint hspec hpc-coveralls happy alex --avoid-reinstalls
    - cabal install --only-dependencies --enable-tests --avoid-reinstalls

script:
    - hlint .
    - cabal configure --enable-tests --enable-library-coverage
    - cabal build
    - cabal test --show-details=always

after_script:
    - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test test-all

notifications:
    - email: true
