language: haskell

ghc:
    - 7.8

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - cabal update
    - cabal install hspec hlint
    - cabal install --only-dependencies --enable-tests

script:
    - hlint .
    - cabal configure --enable-tests --enable-library-coverage
    - cabal build
    - cabal test --show-details=always

after_script:
    - cabal install hpc-coveralls
    - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-fir=test test-all

notifications:
    - email: true
