language: haskell
ghc:
    - 7.8

before_install:
    - "export PATH=$HOME/.cabal/bin:$PATH"
    - "cabal update"

install:
    - "cabal install --only-dependencies --enable-tests"

script:
    - "cabal configure --enable-tests --enable-library-coverage && cabal build && cabal test"

notifications:
    - email: true
