language: haskell

sudo: false

env: CABALVER=1.22 GHCVER=7.8.4

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-1.22
            - ghc-7.8.4
            - haskell-platform
            - alex-3.1.4
            - happy-1.19.5
            - hlint
            - hscolour

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
    - which cabal
    - cabal update
    - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
    - cabal install hspec --avoid-reinstalls
    - cabal install hpc-coveralls --avoid-reinstalls

install:
    - cabal install --only-dependencies --enable-tests --avoid-reinstalls

script:
    - hlint .
    - cabal configure --enable-tests --enable-coverage
    - cabal build
    - cabal test --show-details=always

after_script:
    - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test test-all
