language: haskell

sudo: false

env: CABALVER=1.22 GHCVER=7.8.4

before_install:
    - export PATH=/opt/ghc/$GHCVER/bin:$PATH
    - mkdir -p ~/.local/bin
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - export PATH=~/.local/bin:$PATH
    - stack setup
    - stack init

install:
    - stack build
    - stack install hpc-coveralls
    - stack install hlint

script:
    - stack test spec --no-terminal --coverage

after_script:
    - hlint .
    - ./shc JustSudoku spec

notifications:
    on_failure: always

cache:
    directories:
        - $HOME/.stack
