language: haskell

sudo: false

env: CABALVER=head GHCVER=head

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - cabal-install-head
            - ghc-head
            - happy

before_install:
    - export PATH=$HOME/.cabal/bin:$PATH
    - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
    - cabal update
    - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config
    - cabal install hlint --avoid-reinstalls
    - cabal install hspec --avoid-reinstalls
    - cabal install hpc-coveralls --avoid-reinstalls

install:
    - cabal install --only-dependencies --enable-tests --avoid-reinstalls

script:
    - hlint .
    - cabal configure --enable-tests --enable-coverage
    - cabal build
    - cabal test --show-details=always

after_script:
    - hpc-coveralls --coverage-mode=StrictlyFullLines --exclude-dir=test test-all
