language: haskell

sudo: false

env: CABALVER=1.22 GHCVER=7.8.4

addons:
    apt:
        sources:
            - hvr-ghc
        packages:
            - ghc-7.8.4
            - hlint
            - hscolour

before_install:
    - mkdir -p ~/.local/bin
    - export PATH=~/.local/bin:$PATH
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - export PATH=/opt/ghc/7.8.4/bin:$PATH

install:
    - stack --no-terminal --skip-ghc-check setup
    - stack --no-terminal --skip-ghc-check test --only-snapshot

script:
    - hlint .
    - stack --no-terminal --skip-ghc-check test

after_script:
    # lol
    - hpc-coveralls spec --exclude-dir=test --display-report || true

notifications:
    on_failure: always
